# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool: yarb



- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'youssefabu/media-network-expressjs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'